name: movie_list
description: A simple Movie Listing App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.0
  http: ^0.12.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/