name: flutter_timer
description: Simple Timer built with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.17.0
  equatable: ^0.2.0
  wave: ^0.0.8

flutter:
  uses-material-design: true